### ISSUE TITLE
[crash] java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by VaiN474** [NerdHubMC/Player-Graves#4]
I'm guessing this isn't compatible with the latest Fabric?

log:
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 5/16/19 12:09 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.class_2591$class_2592.method_11035(Ljava/util/function/Supplier;)Lnet/minecraft/class_2591$class_2592;
	at nerdhub.playergraves.PlayerGraves.<clinit>(PlayerGraves.java:29)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.launch.common.FabricLauncherBase.getClass(FabricLauncherBase.java:58)
	at net.fabricmc.loader.language.JavaLanguageAdapter.getClass(JavaLanguageAdapter.java:88)
	at net.fabricmc.loader.language.LanguageAdapter.createInstance(LanguageAdapter.java:30)
	at net.fabricmc.loader.EntrypointStorage$OldEntry.getOrCreate(EntrypointStorage.java:60)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at nerdhub.playergraves.PlayerGraves.<clinit>(PlayerGraves.java:29)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.launch.common.FabricLauncherBase.getClass(FabricLauncherBase.java:58)
	at net.fabricmc.loader.language.JavaLanguageAdapter.getClass(JavaLanguageAdapter.java:88)
	at net.fabricmc.loader.language.LanguageAdapter.createInstance(LanguageAdapter.java:30)
	at net.fabricmc.loader.EntrypointStorage$OldEntry.getOrCreate(EntrypointStorage.java:60)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1326352424 bytes (1264 MB) / 1744830464 bytes (1664 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: 0.2.7+build.127
		fabricloader: 0.4.7+build.147
		playergraves: 1.0.0
	Launched Version: fabric-loader-0.4.7+build.147-1.14.1+build.5
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
```

**Comment by UpcraftLP** [comment]
The mod has not been updated to 1.14.1 yet.
